package compiler

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

// runnerName is the file name of the generated runner.
const runnerName = "main.go"

// kind describes a category of generated runner: tests or benchmarks. The two
// differ in the sources subdirectory, the discovered function prefix, the
// expected *testing parameter, and the directory of the runner.
type kind struct {
	subdir  string // sources subdirectory, e.g. "test"
	command string // generating command, e.g. "so test"
	noun    string // human-readable name used in errors, e.g. "test"
	prefix  string // discovered function name prefix, e.g. "Test"
	param   string // expected *testing.<param> argument, e.g. "T"
	dir     string // directory of the generated runner, e.g. ".sotest"
}

// suite is the discovered functions of one package.
type suite struct {
	label string   // package label for the report, e.g. "so/sync"
	pkg   string   // package name of the sources package, e.g. "sync_test"
	path  string   // import path of the sources package
	names []string // discovered function names
}

// source returns the entry package of the generated program. The runner holds
// code, but no file is written: the runner goes to the Go loader as an overlay,
// and go/packages resolves a package that only the overlay holds. The runner
// directory must not conflict with a directory of the module.
func (k kind) source(root string, code []byte) (source, error) {
	if _, err := os.Stat(filepath.Join(root, k.dir)); err == nil {
		return source{}, fmt.Errorf("%s already exists in %s: %s needs the name for the generated runner",
			k.dir, root, k.command)
	}
	return source{
		dir:     root,
		pattern: "./" + k.dir,
		overlay: map[string][]byte{
			filepath.Join(root, k.dir, runnerName): code,
		},
	}, nil
}

// header returns the generated file header for the kind.
func (k kind) header() string {
	return fmt.Sprintf("// Code generated by %q. DO NOT EDIT.\n\npackage main\n\n", k.command)
}

// collect discovers the functions of dir and returns them as a suite. The
// package of the sources must be importable, so it must have a name of its own.
func (k kind) collect(root, modPath, dir string) (suite, error) {
	pkg, names, err := k.find(dir)
	if err != nil {
		return suite{}, err
	}
	if len(names) == 0 {
		return suite{}, fmt.Errorf("no %sXxx functions found in %s", k.prefix, dir)
	}
	if pkg == "main" {
		return suite{}, fmt.Errorf("%s declares package main: a %s package "+
			"must be importable, so give it a name of its own", dir, k.noun)
	}

	rel, err := moduleRel(root, dir)
	if err != nil {
		return suite{}, err
	}
	// The report labels a suite with the package under test, so the label is
	// the path of the sources directory without its last element.
	return suite{
		label: packageName(root, filepath.Dir(rel)),
		pkg:   pkg,
		path:  modPath + "/" + rel,
		names: names,
	}, nil
}

// find parses every .go file in dir. It returns the package name the directory
// declares and the names of the functions matching the kind's
// `func <Prefix>Xxx(x *testing.<Param>)` shape.
func (k kind) find(dir string) (pkg string, names []string, err error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", nil, err
	}

	fset := token.NewFileSet()
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		// Skip Go test files (_test.go). They let a package keep native
		// Go tests and benchmarks next to the Solod ones (for A/B comparison).
		if strings.HasSuffix(name, "_test.go") {
			continue
		}
		path := filepath.Join(dir, name)
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return "", nil, fmt.Errorf("parse %s: %w", path, err)
		}
		pkg = file.Name.Name
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !k.isName(fn.Name.Name) {
				// Non-matching function, silently skip it.
				continue
			}
			// A function that looks like one of ours but has the wrong
			// signature is almost always a mistake, so reject it loudly
			// rather than skipping it.
			if err := k.checkSig(fn); err != nil {
				return "", nil, fmt.Errorf("%s: %w", path, err)
			}
			names = append(names, fn.Name.Name)
		}
	}

	return pkg, names, nil
}

// isName reports whether name is a valid discovered name: the kind's prefix
// optionally followed by a suffix that does not start with a lowercase letter.
// This mirrors Go's own rule, so a helper like "Testhelper" is not run.
func (k kind) isName(name string) bool {
	if !strings.HasPrefix(name, k.prefix) {
		return false
	}
	if len(name) == len(k.prefix) {
		return true
	}
	r, _ := utf8.DecodeRuneInString(name[len(k.prefix):])
	return !unicode.IsLower(r)
}

// checkSig verifies that fn, whose name already qualifies for the kind, has the
// signature `func(x *testing.<Param>)`.
func (k kind) checkSig(fn *ast.FuncDecl) error {
	arg := strings.ToLower(k.param)
	want := fmt.Sprintf("%s %s must have signature func(%s *testing.%s)",
		k.noun, fn.Name.Name, arg, k.param)
	if fn.Type.TypeParams != nil {
		return fmt.Errorf("%s: it must not be generic", want)
	}
	if fn.Type.Results != nil {
		return fmt.Errorf("%s: it must not return a value", want)
	}
	if !k.isTestingParam(fn.Type.Params.List) {
		return fmt.Errorf("%s", want)
	}
	return nil
}

// isTestingParam reports whether params is a single parameter of type
// *testing.<Param> for the kind.
func (k kind) isTestingParam(params []*ast.Field) bool {
	// A single field may still declare multiple names, e.g. func(a, b *T).
	if len(params) != 1 || len(params[0].Names) > 1 {
		return false
	}
	star, ok := params[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	return ok && pkg.Name == "testing" && sel.Sel.Name == k.param
}

// packageName returns a human-readable name for the package under test, used
// in the report. dir is the package path relative to the module root, so the
// name is that path (e.g. "so/sync"). The package at the module root has no
// such path, so it takes the name of the root directory.
func packageName(root, dir string) string {
	if dir == "." {
		return filepath.Base(root)
	}
	return filepath.ToSlash(dir)
}
