// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/maps", os.Args, []testing.Test{
		{Name: "TestIter", F: TestIter},
		{Name: "TestIter_Empty", F: TestIter_Empty},
		{Name: "TestIter_AfterDelete", F: TestIter_AfterDelete},
		{Name: "TestIter_AfterDeleteAll", F: TestIter_AfterDeleteAll},
		{Name: "TestIter_AfterClear", F: TestIter_AfterClear},
		{Name: "TestIter_AfterGrow", F: TestIter_AfterGrow},
		{Name: "TestIter_Twice", F: TestIter_Twice},
		{Name: "TestKeyBool", F: TestKeyBool},
		{Name: "TestKeyInt8", F: TestKeyInt8},
		{Name: "TestKeyInt16", F: TestKeyInt16},
		{Name: "TestKeyUint64", F: TestKeyUint64},
		{Name: "TestKeyFloat64", F: TestKeyFloat64},
		{Name: "TestKeyFloatZero", F: TestKeyFloatZero},
		{Name: "TestKeyFloatNaN", F: TestKeyFloatNaN},
		{Name: "TestKeyPointer", F: TestKeyPointer},
		{Name: "TestKeyStringEmpty", F: TestKeyStringEmpty},
		{Name: "TestKeyStringLen", F: TestKeyStringLen},
		{Name: "TestKeyStringByte", F: TestKeyStringByte},
		{Name: "TestSetGet", F: TestSetGet},
		{Name: "TestStringValues", F: TestStringValues},
		{Name: "TestHas", F: TestHas},
		{Name: "TestDelete", F: TestDelete},
		{Name: "TestOverwrite", F: TestOverwrite},
		{Name: "TestMissing", F: TestMissing},
		{Name: "TestGrow", F: TestGrow},
		{Name: "TestNewSize", F: TestNewSize},
		{Name: "TestNewSize_One", F: TestNewSize_One},
		{Name: "TestReturnMap", F: TestReturnMap},
		{Name: "TestClear", F: TestClear},
		{Name: "TestDoubleFree", F: TestDoubleFree},
		{Name: "TestDeleteAll", F: TestDeleteAll},
		{Name: "TestRandomInt", F: TestRandomInt},
		{Name: "TestRandomString", F: TestRandomString},
	})
}
