// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/cmp", os.Args, []testing.Test{
		{Name: "TestCompare_Int", F: TestCompare_Int},
		{Name: "TestCompare_IntWidths", F: TestCompare_IntWidths},
		{Name: "TestCompare_Float", F: TestCompare_Float},
		{Name: "TestCompare_FloatNaN", F: TestCompare_FloatNaN},
		{Name: "TestCompare_FloatInf", F: TestCompare_FloatInf},
		{Name: "TestCompare_FloatZero", F: TestCompare_FloatZero},
		{Name: "TestCompare_String", F: TestCompare_String},
		{Name: "TestCompare_Named", F: TestCompare_Named},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestEqual_NaN", F: TestEqual_NaN},
		{Name: "TestEqual_Unsupported", F: TestEqual_Unsupported},
		{Name: "TestLess", F: TestLess},
		{Name: "TestLess_NaN", F: TestLess_NaN},
		{Name: "TestFuncFor_Supported", F: TestFuncFor_Supported},
		{Name: "TestFuncFor_Unsupported", F: TestFuncFor_Unsupported},
	})
}
