// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/mem", os.Args, []testing.Test{
		{Name: "TestTryAlloc", F: TestTryAlloc},
		{Name: "TestTryAllocSlice", F: TestTryAllocSlice},
		{Name: "TestAlloc", F: TestAlloc},
		{Name: "TestAllocDefault", F: TestAllocDefault},
		{Name: "TestAllocSlice", F: TestAllocSlice},
		{Name: "TestAllocSliceDefault", F: TestAllocSliceDefault},
		{Name: "TestAllocSlice_ZeroCap", F: TestAllocSlice_ZeroCap},
		{Name: "TestTryReallocSlice", F: TestTryReallocSlice},
		{Name: "TestReallocSlice", F: TestReallocSlice},
		{Name: "TestReallocSlice_Empty", F: TestReallocSlice_Empty},
		{Name: "TestReallocSlice_ToZero", F: TestReallocSlice_ToZero},
		{Name: "TestFreeNil", F: TestFreeNil},
		{Name: "TestFreeString", F: TestFreeString},
		{Name: "TestFreeStringStats", F: TestFreeStringStats},
		{Name: "TestFreeStringArena", F: TestFreeStringArena},
		{Name: "TestArena", F: TestArena},
		{Name: "TestArena_OutOfMemory", F: TestArena_OutOfMemory},
		{Name: "TestArena_Alignment", F: TestArena_Alignment},
		{Name: "TestArena_ReallocGrow", F: TestArena_ReallocGrow},
		{Name: "TestArena_ReallocShrink", F: TestArena_ReallocShrink},
		{Name: "TestArena_ReallocGrowNotLast", F: TestArena_ReallocGrowNotLast},
		{Name: "TestArena_ReallocShrinkNotLast", F: TestArena_ReallocShrinkNotLast},
		{Name: "TestArena_ReallocOutOfMemory", F: TestArena_ReallocOutOfMemory},
		{Name: "TestArray", F: TestArray},
		{Name: "TestClear", F: TestClear},
		{Name: "TestCompare", F: TestCompare},
		{Name: "TestCopy", F: TestCopy},
		{Name: "TestMove", F: TestMove},
		{Name: "TestSwap", F: TestSwap},
		{Name: "TestSwapByte", F: TestSwapByte},
		{Name: "TestNoAlloc", F: TestNoAlloc},
		{Name: "TestNoAlloc_TryAlloc", F: TestNoAlloc_TryAlloc},
		{Name: "TestNoAlloc_TryAllocSlice", F: TestNoAlloc_TryAllocSlice},
		{Name: "TestTrackerAlloc", F: TestTrackerAlloc},
		{Name: "TestTrackerAllocMultiple", F: TestTrackerAllocMultiple},
		{Name: "TestTrackerAllocError", F: TestTrackerAllocError},
		{Name: "TestTrackerReallocGrow", F: TestTrackerReallocGrow},
		{Name: "TestTrackerReallocShrink", F: TestTrackerReallocShrink},
		{Name: "TestTrackerReallocSameSize", F: TestTrackerReallocSameSize},
		{Name: "TestTrackerReallocError", F: TestTrackerReallocError},
		{Name: "TestTrackerFree", F: TestTrackerFree},
		{Name: "TestTrackerFreeNil", F: TestTrackerFreeNil},
		{Name: "TestTrackerLifecycle", F: TestTrackerLifecycle},
	})
}
