package os

import (
	"unsafe"

	"solod.dev/so/c"
)

// CreateTemp creates a new temporary file in the directory dir,
// opens the file for reading and writing, and returns the resulting file.
// The filename is generated by taking pattern and adding a random string to the end.
// The file is created with mode 0o600 (before umask).
//
// If dir is the empty string, CreateTemp uses the default directory
// for temporary files, as returned by [TempDir].
// The caller can use the file's Name method to find the pathname of the file.
// It is the caller's responsibility to remove the file when it is no longer needed.
//
// Writes the path of the created file into buf. buf must hold the directory,
// the pattern, six random characters, and a null terminator. Panics if buf
// is too small. The name in the returned File is a view into buf.
func CreateTemp(buf []byte, dir, pattern string) (File, error) {
	tmpl := buildTempTemplate(buf[:0], dir, pattern)
	tmplPtr := (*c.Char)(unsafe.SliceData(tmpl))
	fd := mkstemp(tmplPtr)
	if fd < 0 {
		return File{}, mapError()
	}
	fp := fdopen(fd, "w+b")
	if fp == nil {
		fdclose(fd)
		return File{}, mapError()
	}
	name := string(tmpl[:len(tmpl)-1])
	return File{fd: fp, name: name}, nil
}

// MkdirTemp creates a new temporary directory in the directory dir
// and returns the pathname of the new directory.
// The new directory's name is generated by adding a random string to the end of pattern.
// The directory is created with mode 0o700 (before umask).
//
// If dir is the empty string, MkdirTemp uses the default directory
// for temporary files, as returned by TempDir.
// It is the caller's responsibility to remove the directory when it is no longer needed.
//
// Writes the path of the created directory into buf. buf must hold the parent
// directory, the pattern, six random characters, and a null terminator.
// Panics if buf is too small. The returned string is a view into buf.
func MkdirTemp(buf []byte, dir, pattern string) (string, error) {
	tmpl := buildTempTemplate(buf[:0], dir, pattern)
	tmplPtr := (*c.Char)(unsafe.SliceData(tmpl))
	result := mkdtemp(tmplPtr)
	if result == nil {
		return "", mapError()
	}
	return string(tmpl[:len(tmpl)-1]), nil
}

// buildTempTemplate builds a null-terminated template string for mkstemp/mkdtemp.
// The template ends with "XXXXXX" as required by these functions.
// Panics if buf is too small for the template.
func buildTempTemplate(buf []byte, dir, pattern string) []byte {
	if dir == "" {
		dir = TempDir()
	}
	sep := "/"
	if dir == "" || dir[len(dir)-1] == '/' {
		sep = ""
	}
	// The template holds the directory, the separator, the pattern,
	// six random characters, and a null terminator.
	if cap(buf) < len(dir)+len(sep)+len(pattern)+7 {
		panic("os: buffer too small")
	}
	buf = append(buf, dir...)
	buf = append(buf, sep...)
	buf = append(buf, pattern...)
	buf = append(buf, "XXXXXX"...)
	buf = append(buf, 0) // null terminator
	return buf
}

// TempDir returns the default directory to use for temporary files.
// On Unix systems, it returns $TMPDIR if non-empty, else /tmp.
// The directory is neither guaranteed to exist nor have accessible permissions.
func TempDir() string {
	dir := Getenv("TMPDIR")
	if dir != "" {
		return dir
	}
	return "/tmp"
}
