// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/slices", os.Args, []testing.Test{
		{Name: "TestMake", F: TestMake},
		{Name: "TestMakeCap", F: TestMakeCap},
		{Name: "TestAppend", F: TestAppend},
		{Name: "TestAppend_Grow", F: TestAppend_Grow},
		{Name: "TestAppend_Nil", F: TestAppend_Nil},
		{Name: "TestExtend", F: TestExtend},
		{Name: "TestExtend_Nil", F: TestExtend_Nil},
		{Name: "TestExtend_Empty", F: TestExtend_Empty},
		{Name: "TestClone", F: TestClone},
		{Name: "TestClone_Empty", F: TestClone_Empty},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestEqual_Strings", F: TestEqual_Strings},
		{Name: "TestEqual_Floats", F: TestEqual_Floats},
		{Name: "TestEqual_Structs", F: TestEqual_Structs},
		{Name: "TestIndex", F: TestIndex},
		{Name: "TestContains", F: TestContains},
		{Name: "TestMinMax_Ints", F: TestMinMax_Ints},
		{Name: "TestMinMax_Strings", F: TestMinMax_Strings},
		{Name: "TestMinMaxFunc", F: TestMinMaxFunc},
		{Name: "TestIsSorted", F: TestIsSorted},
		{Name: "TestIsSortedFunc", F: TestIsSortedFunc},
		{Name: "TestSort_Ints", F: TestSort_Ints},
		{Name: "TestSort_Float64s", F: TestSort_Float64s},
		{Name: "TestSort_Strings", F: TestSort_Strings},
		{Name: "TestSort_Empty", F: TestSort_Empty},
		{Name: "TestSortFunc", F: TestSortFunc},
		{Name: "TestSortFunc_Nil", F: TestSortFunc_Nil},
		{Name: "TestSortStableFunc_Ints", F: TestSortStableFunc_Ints},
		{Name: "TestSortStableFunc_Float64s", F: TestSortStableFunc_Float64s},
		{Name: "TestSortStableFunc_Strings", F: TestSortStableFunc_Strings},
		{Name: "TestSorter", F: TestSorter},
		{Name: "TestSorter_NilCompare", F: TestSorter_NilCompare},
		{Name: "TestSortWith", F: TestSortWith},
		{Name: "TestSortStableWith", F: TestSortStableWith},
		{Name: "TestSort_LargeRandom", F: TestSort_LargeRandom},
		{Name: "TestSort_LargeEqual", F: TestSort_LargeEqual},
		{Name: "TestSort_LargeReversed", F: TestSort_LargeReversed},
		{Name: "TestSortStable_Random", F: TestSortStable_Random},
		{Name: "TestSortStable_Sorted", F: TestSortStable_Sorted},
		{Name: "TestSortStable_Reversed", F: TestSortStable_Reversed},
		{Name: "TestSort_Adversary", F: TestSort_Adversary},
	})
}
